INSERT INTO category (name, created_at, updated_at) VALUES
                                                        ('Category A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category G', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category H', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category I', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category J', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category K', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category L', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category M', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category O', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category P', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category Q', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category R', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category S', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                        ('Category T', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO task (title, description, category_id, priority, status, created_at, updated_at) VALUES
                                                                                                 ('Task 1', 'Description for Task 1', 1, 'LOW', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 2', 'Description for Task 2', 2, 'MEDIUM', 'PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 3', 'Description for Task 3', 3, 'HIGH', 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 4', 'Description for Task 4', 4, 'URGENT', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 5', 'Description for Task 5', 5, 'LOW', 'PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 6', 'Description for Task 6', 6, 'MEDIUM', 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 7', 'Description for Task 7', 7, 'HIGH', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 8', 'Description for Task 8', 8, 'URGENT', 'PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 9', 'Description for Task 9', 9, 'LOW', 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 10', 'Description for Task 10', 10, 'MEDIUM', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 11', 'Description for Task 11', 11, 'HIGH', 'PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 12', 'Description for Task 12', 12, 'URGENT', 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 13', 'Description for Task 13', 13, 'LOW', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 14', 'Description for Task 14', 14, 'MEDIUM', 'PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 15', 'Description for Task 15', 15, 'HIGH', 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 16', 'Description for Task 16', 16, 'URGENT', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 17', 'Description for Task 17', 17, 'LOW', 'PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 18', 'Description for Task 18', 18, 'MEDIUM', 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 19', 'Description for Task 19', 19, 'HIGH', 'PENDING', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                 ('Task 20', 'Description for Task 20', 20, 'URGENT', 'PROGRESS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
